version: '3'

services:
  ats-discovery-service:
    container_name: 'ats-discovery-service'
    build: ./ats-discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ats-configuration-service-server:
    container_name: 'ats-configuration-service-server'
    build: ./ats-configuration-service-server
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ats-mail-resume-fetcher:
    container_name: 'ats-mail-resume-fetcher'
    build: ./ats-mail-resume-fetcher
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - ats-discovery-service
      - ats-resume-parser
    depends_on:
      - ats-discovery-service
    restart: on-failure

  ats-resume-parser:
    container_name: 'ats-resume-parser'
    build: ./ats-resume-parser
    ports:
      - "5000:5000"
    links:
      - ats-discovery-service
    depends_on:
      - ats-discovery-service
    environment:
      - ATS_DISCOVERY_SERVICE_URL=http://ats-discovery-service:8761/eureka/

  ats-gateway-service:
    container_name: 'ats-gateway-service'
    build: ./ats-gateway-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - 8082

  ats-masterdata-service:
    container_name: 'ats-masterdata-service'
    build: ./ats-masterdata-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ats
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: true




