server:
  port: 8888

spring:
  application:
    name: ats-configuration-server-service
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/v0idFuncti0n/ats-configuration-files'
          default-label: master
          clone-on-start: true