server:
  port: 8888

spring:
  application:
    name: ats-configuration-server-service
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/v0idFuncti0n/ATS'
          default-label: master
          search-paths: ats-configuration-files

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/v0idFuncti0n/ATS'
          default-label: master
          search-paths: ats-configuration-files

server:
  port: 8080