spring:
  application:
    name: 'ats-mail-resume-fetcher'

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://ats-discovery-service:8761/eureka
