spring:
  application:
    name: 'ats-masterdata-service'
  datasource:
    url: jdbc:mysql://localhost:3306/ats
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/ats
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://ats-discovery-service:8761/eureka
