server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: false
    fetch-registry: false
  server:
    expected-client-renewal-interval-seconds: 3
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
  instance:
    lease-expiration-duration-in-seconds: 90

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080
